name: workshop_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch  # Ensure CUDA-compatible PyTorch is installed
  - cudatoolkit  # Installs CUDA libraries for GPU support
  - faiss-cpu  # Use 'faiss-gpu' if your GPU supports it
  - numpy
  - sqlite
  - presidio-analyzer
  - presidio-anonymizer
  - accelerate
  - transformers
  - huggingface-hub
  - fastapi
  - uvicorn
  - sentence-transformers
  - pydantic
  - pip:
      - ctransformers[cuda]  # Install CUDA-compatible version of ctransformers
