name: workshop_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - faiss-cpu
  - numpy
  - sqlite
  - pip:
      - fastapi==0.104.1
      - uvicorn==0.24.0
      - sentence-transformers==2.2.2
      - transformers==4.36.2
      - accelerate>=0.26.0
      - ctransformers==0.2.27
      - pydantic==2.4.2
      - huggingface-hub==0.19.4